const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const state={name:'Matangi',opened:new Set(),hearts:new Set(),sound:false,starIndex:0,reasonIndex:0};
const compliments=['You make kindness look powerful.','Your smile changes the weather in a room.','You are the kind of beautiful that time cannot touch.','The world is gentler because you are in it.','You make being yourself look like an art form.','You are someone worth choosing, every single day.'];
const reasons=['You listen with your whole heart.','You make ordinary days feel worth remembering.','Your laugh is still my favorite sound.','You care in all the tiny ways that matter most.','You make me want to be softer, braver, and better.','You understand things I have not found words for yet.','You are strong without losing your tenderness.','You make love feel safe and exciting at the same time.','You are wonderfully, unmistakably you.','Even ten reasons are nowhere near enough.'];
const futureMessages={adventure:'Pack light. I am bringing snacks, bad directions, and a lifetime of holding your hand.',ordinary:'Coffee, tangled hair, nowhere to rush — proof that the smallest days can still be my favorites.',dream:'We will build it slowly, laugh when the plan changes, and celebrate every impossible little step.'};
$$('[data-name]').forEach(node=>node.textContent=state.name);
$('#begin-button').addEventListener('click',()=>{$('#welcome').hidden=true;$('#first-reveal').hidden=false;burst(28);chime(440);$('#continue-button').focus()});
$('#continue-button').addEventListener('click',()=>{$('#first-reveal').hidden=true;$('#universe').hidden=false;$('#universe').scrollIntoView({behavior:'smooth'});burst(40);chime(520)});
$$('[data-open]').forEach(card=>card.addEventListener('click',()=>openSurprise(card.dataset.open)));$$('[data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));$$('dialog').forEach(dialog=>{dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});dialog.addEventListener('close',()=>document.body.classList.remove('dialog-open'))});
function openSurprise(key){const dialog=$(`[data-dialog="${key}"]`);if(!dialog)return;if(key!=='finale')markOpened(key);dialog.showModal();document.body.classList.add('dialog-open');chime(620)}
function markOpened(key){if(state.opened.has(key))return;state.opened.add(key);const card=$(`[data-open="${key}"]`);card?.classList.add('opened');const label=card?.querySelector('.card-status');if(label)label.textContent='Discovered';$('#progress-count').textContent=state.opened.size;if(state.opened.size===6)unlockFinale()}
function unlockFinale(){const card=$('#final-card');card.disabled=false;card.classList.remove('locked');$('.card-icon',card).textContent='🎁';$('.card-status',card).textContent='Ready';$('#final-hint').textContent='You found every light — open me';burst(36);chime(780)}
$('#catch-star').addEventListener('click',()=>{$('#star-message').textContent=compliments[state.starIndex%compliments.length];state.starIndex+=1;$('.star-glow').textContent=['✦','✧','★','⋆'][state.starIndex%4];chime(660+state.starIndex*30)});
$('#reason-slip').addEventListener('click',()=>{$('#reason-text').textContent=reasons[state.reasonIndex%reasons.length];state.reasonIndex+=1;chime(480+state.reasonIndex*20)});
$$('[data-future]').forEach(button=>button.addEventListener('click',()=>{$$('[data-future]').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');$('#future-answer').textContent=futureMessages[button.dataset.future];chime(560)}));
$$('[data-quiz]').forEach(button=>button.addEventListener('click',()=>{$$('[data-quiz]').forEach(item=>item.classList.remove('selected'));button.classList.add('selected');$('#quiz-answer').textContent='Correct. Somehow every answer was the right answer. ♡';chime(720)}));
$$('#candles button').forEach(button=>button.addEventListener('click',()=>{button.setAttribute('aria-pressed','true');button.textContent='💨';chime(420);const allOut=$$('#candles button').every(candle=>candle.getAttribute('aria-pressed')==='true');if(allOut){$('#wish-result').textContent='Wish sent. The universe has excellent reception. ✦';burst(70);chime(840)}}));
$$('[data-heart]').forEach(heart=>heart.addEventListener('click',()=>{state.hearts.add(heart.dataset.heart);heart.classList.add('found');heart.textContent='♥';heart.disabled=true;$('#heart-count').textContent=state.hearts.size;chime(700+state.hearts.size*60);if(state.hearts.size===3){setTimeout(()=>{$('#bonus-dialog').showModal();document.body.classList.add('dialog-open');burst(48)},450)}}));
const holdButton=$('#hold-button');let holdTimer;function startHold(event){event.preventDefault();holdButton.classList.add('holding');holdTimer=setTimeout(revealFinale,1800)}function cancelHold(){clearTimeout(holdTimer);holdButton.classList.remove('holding')}function revealFinale(){holdButton.classList.remove('holding');$('#finale-ready').hidden=true;$('#final-message').hidden=false;burst(160);chime(900)}
holdButton.addEventListener('pointerdown',startHold);holdButton.addEventListener('pointerup',cancelHold);holdButton.addEventListener('pointerleave',cancelHold);holdButton.addEventListener('keydown',event=>{if((event.key===' '||event.key==='Enter')&&!event.repeat)startHold(event)});holdButton.addEventListener('keyup',event=>{if(event.key===' '||event.key==='Enter')cancelHold()});$('#celebrate-again').addEventListener('click',()=>burst(160));
$('#sound-toggle').addEventListener('click',event=>{state.sound=!state.sound;event.currentTarget.setAttribute('aria-pressed',String(state.sound));event.currentTarget.textContent=state.sound?'Sound on ♪':'Sound off';if(state.sound)chime(640)});
function chime(frequency=600){if(!state.sound)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;const context=chime.context||(chime.context=new AudioContext());const oscillator=context.createOscillator();const gain=context.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,context.currentTime);gain.gain.exponentialRampToValueAtTime(.08,context.currentTime+.015);gain.gain.exponentialRampToValueAtTime(.0001,context.currentTime+.42);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.45)}
function burst(count=80){if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const canvas=$('#confetti');const context=canvas.getContext('2d');const ratio=window.devicePixelRatio||1;canvas.width=innerWidth*ratio;canvas.height=innerHeight*ratio;context.scale(ratio,ratio);const colors=['#ff78b9','#ffd76a','#9bf4cf','#8ebdff','#ffffff'];const pieces=Array.from({length:count},()=>({x:innerWidth/2+(Math.random()-.5)*120,y:innerHeight*.38,vx:(Math.random()-.5)*12,vy:-Math.random()*9-3,size:Math.random()*7+3,color:colors[Math.floor(Math.random()*colors.length)],spin:Math.random()*Math.PI}));let frame=0;function draw(){context.clearRect(0,0,innerWidth,innerHeight);pieces.forEach(piece=>{piece.x+=piece.vx;piece.y+=piece.vy;piece.vy+=.2;piece.spin+=.13;context.save();context.translate(piece.x,piece.y);context.rotate(piece.spin);context.fillStyle=piece.color;context.fillRect(-piece.size/2,-piece.size/3,piece.size,piece.size*.65);context.restore()});frame+=1;if(frame<150)requestAnimationFrame(draw);else context.clearRect(0,0,innerWidth,innerHeight)}draw()}

if(window.matchMedia('(pointer:fine)').matches&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){$$('.surprise-card:not(.card-final)').forEach(card=>{card.addEventListener('pointermove',event=>{const box=card.getBoundingClientRect();const x=(event.clientX-box.left)/box.width-.5;const y=(event.clientY-box.top)/box.height-.5;card.style.setProperty('--rx',`${-y*4}deg`);card.style.setProperty('--ry',`${x*5}deg`)});card.addEventListener('pointerleave',()=>{card.style.setProperty('--rx','0deg');card.style.setProperty('--ry','0deg')})})}
